In [1]:
import numpy as np

In [4]:
a = np.zeros((3))
print a

[ 0.  0.  0.]


In [6]:
b = np.ones((2,3))
print b

[[ 1.  1.  1.]
 [ 1.  1.  1.]]


In [12]:
c = np.random.randint(1,10,(2,3,4))
print c

[[[1 9 8 3]
  [7 9 3 4]
  [5 4 5 9]]

 [[1 3 3 7]
  [5 8 6 7]
  [8 8 3 9]]]


In [10]:
d = np.arange(0,11,2)
print d

[ 0  2  4  6  8 10]
